# Generated by Django 4.1 on 2022-08-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_grade',
            field=models.CharField(default='80%', max_length=100),
        ),
    ]
