# Generated by Django 4.1 on 2022-08-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classification',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
