# Generated by Django 4.1 on 2022-08-24 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_student_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(default='08-15-2022', max_length=100)),
                ('end', models.CharField(default='12-15-2022', max_length=100)),
                ('final_grade', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='time',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(through='main_app.Enrollment', to='main_app.student'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.course'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.student'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('students', 'course')},
        ),
    ]
