# Generated by Django 4.1 on 2022-08-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_student_current_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='current_grade',
        ),
        migrations.AddField(
            model_name='student',
            name='gpa',
            field=models.CharField(default='3.5', max_length=100),
        ),
    ]
